create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    username varchar(255) not null unique,
    role varchar(50) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table posts (
    id bigint generated by default as identity primary key,
    author_id bigint not null,
    title varchar(200) not null,
    description varchar(5000),
    status varchar(50) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_post_author
        foreign key (author_id)
        references users(id)
);

create table locations (
    id bigint auto_increment primary key,
    post_id bigint not null,
    name varchar(255) not null,
    description varchar(2000),
    region varchar(255),
    elevation integer,
    source varchar(50) not null,
    order_index integer not null,
    latitude double not null,
    longitude double not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_location_post
        foreign key (post_id)
        references posts(id)
);

create table media (
    id bigint auto_increment primary key,
    post_id bigint not null,
    url varchar(1024) not null,
    type varchar(50) not null,
    status varchar(50) not null,
    order_index integer not null,
    cover boolean not null,
    file_size bigint not null,
    mime_type varchar(255) not null,
    width integer,
    height integer,
    duration integer,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_media_post
        foreign key (post_id)
        references posts(id)
);

create table location_terrain_types (
    location_id bigint not null,
    terrain_type varchar(50) not null,
    constraint fk_location_terrain_location
        foreign key (location_id)
        references locations(id)
);

create index idx_post_author on posts(author_id);
create index idx_post_status on posts(status);